FROM scratch
MAINTAINER Van Simmons <van.simmons@computecycles.com>

VOLUME ["/lib", "/usr/lib"]

COPY ./.build/x86_64-unknown-linux/debug/echoserver ./echoserver

ENV LD_LIBRARY_PATH=/swift_runtime/usr/lib/swift/linux:/swift_runtime/usr/lib/x86_64-linux-gnu:/swift_runtime/lib/x86_64-linux-gnu
ENTRYPOINT ["/swift_runtime/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2"]
CMD ["./echoserver"]

