FROM scratch
MAINTAINER Van Simmons <van.simmons@computecycles.com>

VOLUME ["/lib", "/usr/lib"]

COPY ./.build/aarch64-unknown-linux/debug/echoserver ./echoserver

ENV LD_LIBRARY_PATH=swift_runtime/usr/lib/swift/linux:/swift_runtime/usr/lib/aarch64-linux-gnu:/swift_runtime/lib/aarch64-linux-gnu
ENTRYPOINT ["/lib/ld-linux-aarch64.so.1"]
CMD ["./echoserver"]

